### PR TITLE
New Challenge Named Variables added

### PR DESCRIPTION
**Pull request by 0vai5**
C## Variables Challenge

### Overview
This challenge introduces users to fundamental concepts related to JavaScript variables, focusing on variable declaration, reassignment, and scoping rules.

### Tasks Covered
1. **Task 1: Variable Declaration with `var`**
   - Learn how to declare variables using the `var` keyword and log their values to the console.

2. **Task 2: Variable Declaration with `let`**
   - Understand the difference between `var` and `let` by declaring variables with `let` and observing their behavior when reassigned.

3. **Task 3: Using `const` for Constants**
   - Explore the usage of `const` to declare constants and understand why they cannot be reassigned.

4. **Task 4: Type Checking with `typeof`**
   - Learn how to use the `typeof` operator to check the data type of variables in JavaScript.

5. **Task 5: Variable Reassignment**
   - Practice reassigning variables declared with `let` and observe the outcome.

6. **Task 6: Error Handling with Constants**
   - Attempt to reassign a value to a constant declared with `const` and observe the resulting error.

### Key Learnings

- **Variable Scoping**: Understand the scope of variables declared with `var`, `let`, and `const`.
- **Type Checking**: Use `typeof` to determine the data type of variables dynamically.
- **Best Practices**: Learn best practices for variable declaration and usage in JavaScript.

### Additional Notes
- This challenge is designed to enhance understanding of JavaScript variables through practical examples.
- Contributions should focus on clarity, educational value, and adherence to JavaScript best practices.

### CODE REVIEW

**Review by sadanandpai — CHANGES_REQUESTED** [review]
Lets include only challenges.

No key learning and feature requests. Also please follow the standards used for other challenges

**Comment by 0vai5** [comment]
> Lets include only challenges.
> 
> 
> 
> No key learning and feature requests. Also please follow the standards used for other challenges

Will you be closing the pull request

**Comment by 0vai5** [comment]
I have removed the feature requests and also removed the key learnings

**Comment by 0vai5** [comment]
Whats the update regarding the changes that were made by me @sadanandpai

**Comment by sadanandpai** [comment]
image

Fix the headers. An outcome section is not needed. Please follow the other challenges for reference
Also move it to concepts section

**Comment by 0vai5** [comment]
updated as per the requirments @sadanandpai

**Review by sadanandpai — APPROVED** [review]

**Pull request merged**
